#!/usr/bin/env bash
set -e
pair=wagusd
sources=(
  coingeco
  gateio
  uniswap
)

case $1 in
  coingeco) {
    setzer x-price "$1" wagyuswap:usd
  };;
  uniswap) {
    setzer x-price "$1" WAGUSD
  };;
  gateio) {
    setzer x-price "$1" WAGYU:USDT
  };;
  *) {
    setzer price $pair coingeco
  };;
esac
