#!/usr/bin/env bash
set -e
pair=mtrgusd
sources=(
  coingeco
  kraken
  livecoinwatch
)

case $1 in
  coingeco) {
    setzer x-price "$1" meter-governance:usd
  };;
  kraken) {
    setzer x-price "$1" meter-governance:usdt
  };;
  livecoinwatch) {
    setzer x-price "$1" mtrg:usd
  };;
  *) {
#    setzer --price-commands "-$1-" $pair "${sources[@]}"
    setzer price $pair livecoinwatch
  };;
esac
