#!/usr/bin/env bash
set -e
pair=vlxusd
sources=(
  coingeco
  exmo
  bitrex
  hitbtc
  probit
  pro_changelly
  fmfw
)

case $1 in
  exmo|hitbtc) {
    vlx_btc=$(setzer x-price "$1" vlx:btc)
    btc_usd=$(setzer price btcusd)
    price=$(setzer --format "$(bc -l <<<"$vlx_btc * $btc_usd")")
    setzer --format "$(bc -l <<<"1 / $price")"
  };;
  coingeco) {
    price=$(setzer x-price "$1" velas:usd)
    setzer --format "$(bc -l <<<"1 / $price")"
  };;
  bitrex|probit|pro_changelly|fmfw) {
    price=$(setzer x-price "$1" vlx:usdt)
    setzer --format "$(bc -l <<<"1 / $price")"
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
