#!/usr/bin/env bash
set -e
pair=usdvlx
sources=(
  coingeco
  exmo
  hitbtc
  gateio
  kucoin
)

case $1 in
  exmo|hitbtc|coingeco|bitrex|probit|pro_changelly|fmfw) {
    vlxusd=$(setzer price vlxusd $1)
    setzer --format "$(bc -l <<<"1 / $vlxusd")"
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
